  services:
    api:
      build: ./api
      ports:
        - "8000:8000"
      volumes:
        - ../../models:/models  # Монтирует models для динамического доступа

    app:
      build: ./app
      ports:
        - "8501:8501"
      depends_on:
        - api
